#versão do docker-compose
version: "3.0"

#serviço da aplicação que irá coletar os tweets
services:
    app-python-coleta-hashtags-twitter:
        
        #construindo a imagem a partir de um dockerfile
        build:            
            #caminho do dockerfile
            dockerfile: ./app-python-coleta-hashtags-twitter.dockerfile
            context: .
        
        #nome do usuário no dockerhub / nome da imagem
        image: lucasdearaujo1/app-python-coleta-hashtags-twitter:v1
        
        #nome do container
        container_name: app-python-coleta-hashtags-twitter
        
        #inserindo o container na rede itau para comunicação com os outros containers da mesma rede
        networks:
            - case-itau
    
#criando rede para a comunicação dos containers
networks:
    case-itau:        
        #utilizando o driver default
        driver: bridge