#versão do docker-compose
version: "3.0"

services:
    #serviço do banco de dados mysql que irá armazenar os tweets
    db-mysql:
                
        #imagem do MySQL já pronta à ser utilizada
        image: mysql:5.7
        
        #nome do container
        container_name: db-mysql
        
        #variáveis de ambiente para criação da base de dados, com o usuário root e sem a necessidade de informar a senha
        environment:
            - MYSQL_DATABASE=DB_HASHTAGS
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes